### ISSUE TITLE
AudioVisual should have uuid

### ISSUE THREAD

**Issue by khankuan** [filestack/filestack-python#20]
Hi, the av_convert method returns a AudioVisual object but there is no reference to know what is the conversion request id and hence it is impossible to know which handle has been converted from the callback.

**Comment by staturecrane** [comment]
Hi @khankuan! Thanks for the comment.

The AudioVisual object is intended just as a temporary state, that allows you to check the status  (av_object.status) and then convert to filelink once the conversion has been completed (av_object.to_filelink()). Are you saying there is additional information while in that state you would like to know, or are you referring to the eventual information you get back once the conversion is complete?

**Comment by khankuan** [comment]
Hi, having the status and to_filelink methods are good. Unfortunately, there is a chance there the server would be unavailable before the conversion is done. When the server is up and running and received the webhook for conversion completed, it does not know how to map the conversion result to the original av_object. It would be helpful if we add `av_object.get` that is similar to `av_object.status` but returns the full response (which contains the conversion id) instead of just the status.

**Comment by staturecrane** [comment]
@khankuan Gotcha. That makes complete sense. I will submit this for approval immediately and let you know how quickly you can expect the functionality.

**Comment by staturecrane** [comment]
@khankuan This functionality is scheduled for our next release.

**Comment by staturecrane** [comment]
@khankuan A pull request for this feature has been created. We will make a new release once it has been approved.

**Comment by khankuan** [comment]
Thanks :)

**Comment by staturecrane** [comment]
This feature has been released. Closing issue
