### ISSUE TITLE
filelink.get_metadata returns response object when error

### ISSUE THREAD

**Issue by khankuan** [filestack/filestack-python#21]
The following returns invalid metadata.
```
filelink = client.upload(url)
metadata = filelink.get_metadata()
print(metadata)

TypeError: 'Response' object does not support item assignment
<Response [400]>
```

1) The metadata url returned 400 bad request.
2) The `utils.make_call` should throw an exception instead of returning the failed response without errors.

Cheers

**Comment by staturecrane** [comment]
@khankuan Yes, this can be added. Thanks for the catch.

**Comment by staturecrane** [comment]
@khankuan This functionality was added as part of newest release. Closing this for now. Thanks!

**Comment by khankuan** [comment]
Works well thanks!
