### ISSUE TITLE
Add Minify CSS task

### ISSUE THREAD

**Issue by bkwi** [filestack/filestack-python#45]
New `minify_css` task should be added to [`ImageTransformationMixin`](https://github.com/filestack/filestack-python/blob/develop/filestack/mixins/imagetransformation.py#L5)

Filestack docs can be found [here](https://www.filestack.com/docs/api/processing/#minify-css)

This task takes two arguments: `level` and `gzip`.
It should be implemented similarly to `resize`, `crop` or `rotate`.

Expected usage:
```python
filelink.minify_css()
filelink.minify_css(level=1, gzip=False)
```

Tests are required.

For reference, please see PR https://github.com/filestack/filestack-python/pull/38

**Comment by KIRA009** [comment]
Is the `filelink` a `Client` object? Can the link to the css file that needs to be minified, be outside of filestack.com, or should it belong to this domain exclusively?

**Comment by bkwi** [comment]
@KIRA009 `Filelink` and `Client` objects are not the same.

Link to css file does not have to be a filestack.com url, something like this will work:
```
https://cdn.filestackcontent.com/API_KEY/minify_css/https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css
```
Please see how other tasks are implemented.
